# Use official Python image
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Copy backend code
COPY backend/ /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8000

# Start backend
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
