# Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy frontend code
COPY frontend/ /app

# Install dependencies
RUN npm install

# Build
RUN npm run build

# Install serve to serve static files
RUN npm install -g serve

# Expose port
EXPOSE 4173

# Start frontend
CMD ["serve", "-s", "dist", "-l", "4173"]
